version: "3.8"

services:
  hono-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: hono-api
    ports:
      - "8787:8787"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--no-verbose",
          "--tries=1",
          "--spider",
          "http://localhost:8787/",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s

  # オプションで必要に応じてリバースプロキシを追加
  # nginx:
  #   image: nginx:alpine
  #   container_name: nginx-proxy
  #   ports:
  #     - "80:80"
  #   volumes:
  #     - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
  #   depends_on:
  #     - hono-app
